import Head from "next/head";
import styled from "styled-components";
import ContactPage from "../Components/ContactPage/ContactPage";

const Heading = styled.h1`
  color: #000;
  font-size: 3rem;
  font-weight: bold;
`;

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactPage />
    </>
  );
}
