import Head from "next/head";
import styled from "styled-components";
import HomePage from "../Components/HomePage/HomePage";

const Hero = styled.div`
  height: 60vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #fff;
`;

const Heading = styled.h1`
  color: #000;
  font-size: 4rem;
  font-weight: 900;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
      <Hero>
        <heading>Home page</heading>
      </Hero>
    </>
  );
}
