import Head from "next/head";
// import Navbar from "../Components/Navbar";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

const Hero = styled.div`
  height: 60vh;
  display: flex;
  justify-content: center;
  align-items: center;
  color: white;
`;

const Heading = styled.h1`
  color: white;
  font-size: 3rem;
  font-weight: bold;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <heading>Home pages</heading>
      </Hero>
    </>
  );
}
