import Head from "next/head";
// import Navbar from "../Components/Navbar";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

const Hero = styled.div`
  height: 60vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #fff;
`;

const Heading = styled.h1`
  color: #000;
  font-size: 4rem;
  font-weight: 900;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
        />
      </Head>
      <Hero>
        <heading>Home page</heading>
      </Hero>
    </>
  );
}
